// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Prisma CLI (migrations) requires mysql:// scheme and sslmode=require;
    // the runtime adapter uses mariadb:// with ssl=true
    url: process.env['DATABASE_URL']
      ?.replace('mariadb://', 'mysql://')
      .replace('ssl=true', 'sslaccept=strict'),
  },
});
